export enum Colors {
  TextPrimary = 'text-primary',
  TextSecondary = 'text-secondary',
  TextSuccess = 'text-success',
  TextWarning = 'text-warning',
  TextDanger = 'text-danger',
  BgPrimary = 'bg-primary',
  BgSecondary = 'bg-secondary',
  BgSuccess = 'bg-success',
  BgWarning = 'bg-warning',
  BgDanger = 'bg-danger',
  BorderPrimary = 'border-primary',
  BorderSecondary = 'border-secondary',
  BorderSuccess = 'border-success',
  BorderWarning = 'border-warning',
  BorderDanger = 'border-danger',
}
